### PR TITLE
Active Record Project

### PR DESCRIPTION
**Pull request by denisdiaconu**
Hello!

We are making a pull request for the Micro-Reddit project, which required us to create the models and associations for a forum application.

Thank you for your time and review.

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle: 
### Hi @denisdiaconu and @arikarim  ! 👋 👋  

### You have done well so far :clap: :heavy_check_mark: You've demonstrated good knowledge of active records, models, and associations.

Here's what is preventing me from approving this PR:

:x: You have some rubocop errors, most of which can be fixed by runningrubocop -a` in your terminal.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by arikarim** [comment]
Thanks for the review. we fixed all the errors. 
Note that there are 3 linter errors remain caused by the node modules if you test it in local machine.

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work. 💻 👀 ✨ 
- Good work correcting most of the errors previously pointed out.

## However, there are some changes required 👀 🧰 🔨 🔧 

- Please make sure to fix the Rubocop errors you mention in your most recent comment in the PR before requesting a new code review.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by arikarim** [comment]
Thanks for the review. we fixed all the errors. 
Though the linter errors where caused by node modules and are inside .gitignore but we fixed that too.

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @arikarim and @denisdiaconu  , your project is approved :tada: :tada: :tada: 
You have implemented all minimum requirements for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Pull request merged**
